%%  
 % This file is part of DigitalKhatt IndoPak Font which is licensed under the SIL Open Font License, Version 1.1.
 % Go to https://github.com/DigitalKhatt/indopakfont/blob/main/LICENSE for full license details.
%%

nametable.familyName := "DigitalKhatt IndoPak";
nametable.copyright := "Copyright (c) 2024 Amine Anane, Copyright © 2024 Tarteel Inc.";
lineheight := 135;
penwidth := 135;
joinvector := ljoinvector := rjoinvector := (20,lineheight); 
nuqta := 1.4penwidth;
noondepth := 200;
